### ISSUE TITLE
Initialisation de Hugo

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#10]
@todo init hugo

**Comment by mfr75** [comment]
- [ ] create readme
- [ ] create licence file
- [ ] create how to contribute
- [ ] give details of branches and tags

**Comment by AwebsomeFr** [comment]
J'ai effectué mes premiers tests avec Hugo. J'ai forké le projet et j'ai crée [un dossier indépendant](https://github.com/AwebsomeFr/EcoIndex/tree/master/ecoindex%20with%20Hugo) avec [trois pages buildées accessibles ici](https://github.com/AwebsomeFr/EcoIndex/tree/master/ecoindex%20with%20Hugo/public/main) pour démonstration.

Les pages **à générer** (format markdown) depuis le dossier [content/main/](https://github.com/AwebsomeFr/EcoIndex/tree/master/ecoindex%20with%20Hugo/content/main) reposent sur le template [layout/main/single.html](https://github.com/AwebsomeFr/EcoIndex/tree/master/ecoindex%20with%20Hugo/layouts/main). Le head, header et footer sont importés par le template depuis le dossier [layouts/partials](https://github.com/AwebsomeFr/EcoIndex/tree/master/ecoindex%20with%20Hugo/layouts/partials).

J'ai déjà quelques réserves quant à la liberté de mise en page, mais je préfère ne pas me prononcer, je maitrise encore assez peu le sujet.

**Comment by rlemaire** [comment]
Bonjour,

Je viens de créer une pull request
<https://github.com/cnumr/EcoIndex/pull/11>.

Je suis parti du fork de Julien et j'ai modifié un peu le look&feel en
m'inspirant de la prod actuelle pour voir si tout était faisable, je n'ai
pas rencontré de problème.

J'ai aussi pu internationaliser sans pb.

Je vous laisse relire la PR et me faire des retours éventuellement.

Bonne journée,
--
*Raphaël Lemaire*
lemaire.raphael@gmail.com
*06 70 59 26 34*


Le sam. 25 avr. 2020 à 12:59, Julien Wilhelm <notifications@github.com> a
écrit :
