### ISSUE TITLE
Problème sur les URLs ayant une majuscule dans le protocole.

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#106]
Lorsque l'on teste une URL de type `Https://www.euronews.com` L'analyse ne s'effectue pas en expliquant que l'URL n'est pas valide. 

J'imagine que nous avons un check via une regex avec un `http(s)` quelque part. Il faudrait minifier les caractère ( en JS on peut faire un `toLowerCase()` ) **avant** de vérifier la validité de L'URL.

Ex de l'utilisation d'un `toLowerCase()` en JS : 
```javascript
const url = "HtTp://EuronEwS.Com";
url.toLowerCase();
```

**Comment by yaaax** [comment]
Fixed by e797d80636feb28c73e4256cb8f6411804a1638a
