### ISSUE TITLE
Problème d'encodage d'un texte sur les pages de résultats

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#107]
Dans les pages de résultats, nous avons un soucis d'encodage sur un espace : `&nbsp;` 

Sur le texte apparaissant lorsqu'un site obtient un grade `F`, le texte suivant apparait : 
`On ne va pas se le cacher&nbsp;: ça fait mal. Il est temps d'agir !`
Le texte devrait être : 
`On ne va pas se le cacher : ça fait mal. Il est temps d'agir !`

![Screenshot_20220909_200336_edit_411295271273698](https://user-images.githubusercontent.com/12815769/189434474-cf6fdc50-fdf8-45ec-bed9-5ce3357541f1.jpg)

**Comment by yaaax** [comment]
Fixed by c152f4fa9885335a51404d8369fa37a4a0f20ad9
