### ISSUE TITLE
Problème de largeur du viewport sur mobile

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#108]
Certaines pages ( `résultat de test` et `comment ça marche`) possèdent un problème de largeur du conteneur. 

Certains mots, comme `environementale` ou certains élements, comme les infobulles de résultats sont plus large que le conteneur et  "dépassent" de la page. 

Il faudrait corriger ces soucis et faire que nos utilisateurs et utilisatrices ne soient pas obligés de scroller horizontalement pour afficher la totalité de la page sous mobile. 

Potentiellement, il peut y avoir : 
➡️ Un problème de taille de police d'écriture pour les titres ?
➡️ Un problème de padding/margin sur les éléments infobulles ? 
➡️ Un problème de taille de conteneur trop `petit`

![Screenshot_20220909_200643_com brave browser_edit_411506629386166](https://user-images.githubusercontent.com/12815769/189435488-825f1f3d-64a3-4b0d-935a-c46844e685c9.jpg)
![Screenshot_20220909_200446_com brave browser_edit_411438371038260](https://user-images.githubusercontent.com/12815769/189435491-1f394c5e-4e5a-46df-a4eb-6ceb59d6fab6.jpg)

**Comment by yaaax** [comment]
Fixed by https://github.com/cnumr/EcoIndex/commit/f73b53473335120c7e9c3e7c6b3119c889c55777
See [Fix too large strings breaking layout on mobile](https://gitlab.com/goodimpact/goodimpact-hugo/modules/base-structure/-/commit/c804a6b2162ac0a416827a2024fbf526ff1cf763)
