### ISSUE TITLE
Noscript

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/EcoIndex#110]
There is no `noscript` tag actually.
But user need JavaScript to use EcoIndex.

Should we add one ?

**Comment by yaaax** [comment]
Yes we should!
And ideally give an alternative to the service, without needing to activate JavaScript!

**Comment by AwebsomeFr** [comment]
Of course!

First, let's make the `noscript` tag. 
We can reuse the class "top-warning.". 

I'll try to watch this today.

**Comment by yaaax** [comment]
> Of course!
> 
> First, let's make the `noscript` tag. We can reuse the class "top-warning.".
> 
> I'll try to watch this today.

🙌
