### ISSUE TITLE
Setup Github Actions to deploy code in public folder

### ISSUE THREAD

**Issue by yaaax** [cnumr/EcoIndex#111]
My local command is currently :

```
rm -rf ./public &&
npm install &&
hugo &&
rsync -rpzv -e 'ssh -p12022' ./public/ [username]@[XXX.XXX.XXX.XXX]:/home/ecoindex.neutral.hosting/public_html/
```
_(username and IP hidden)_

⚠️ Please do not use hugo minify. It will be done in the code. At the moment it breaks UI like this ("- " before each menu item) :
<img width="761" alt="broken-ui" src="https://user-images.githubusercontent.com/11678850/189496473-aed9d372-fa4a-4c20-8f11-bfd303227a8e.png">

**Comment by vvatelot** [comment]
closed by #117
