### ISSUE TITLE
Prepare beta release

### ISSUE THREAD

**Issue by yaaax** [cnumr/EcoIndex#113]
Tag, change log, etc.

**Comment by DocRoms** [comment]
Release béta Taguée en `v0.1.0` La release note est disponible ici ➡️ https://github.com/cnumr/EcoIndex/releases/tag/v0.1.0

On fera désormais des évolutions de TAG à chaque MEP, et une release quand on aura atteint un objectif spécifique (plus de beat, fin de nouvelles features, etc...)
