### ISSUE TITLE
Get current EcoIndex login

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#12]
For the next step of Hugo initialisation we must to have the current ecoIndex Login for change few things to the actual code, and get the results with an Ajax request.

Todo : 
- [x] Send a Request to Frederic Bordage

**Comment by DocRoms** [comment]
I received the ids for : 

- [x] Wordpress admin
- [x] Server

**Comment by AwebsomeFr** [comment]
@DocRoms : The source code uploaded yesterday on Google Drive seems to be different of the current version of Ecoindex.fr (ecoindex.fr use a file "processRequest" and there is no match with that name into the archive). It that normal ?
