### ISSUE TITLE
Problème de TimeZone sur les résultats d'audit

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#124]
Lorsque l'on fait un audit, l'affichage de l'heure du test effectué n'est pas à la bonne heure. 

Il faudrait remédier à ça pour que la date affichée soit la bonne. 

![EcoIndexTimeZone](https://user-images.githubusercontent.com/12815769/190118554-5607d7a0-b326-40bc-a453-1bdba7f79604.png)

**Comment by vvatelot** [comment]
Je pense que c'est côté back ça...

**Comment by vvatelot** [comment]
Déployé et PR mergée
