### ISSUE TITLE
Horodatage illisible

### ISSUE THREAD

**Issue by Amael-PE** [cnumr/EcoIndex#135]
L'horodatage actuel est au format : "2022-09-16T22:35:35", en tête de page lorsqu'on regarde les résultats.
Un petit effort pour passer à un affichage user-friendly serait top.

**Comment by vvatelot** [comment]
Merci @Amael-PE pour cette remontée !
De mon côté j'ai ça :
![image](https://user-images.githubusercontent.com/12939091/190857106-d150569b-8380-4585-9117-50e7d3265535.png)

Est ce que l'on parle de la même chose ?

**Comment by Amael-PE** [comment]
On parle de la même chose oui ^^.
J'ai la même chose que toi si je teste leroymerlin.fr, mais avec resilio-solutions.com j'obtiens :
"Calculé le 2022-09-17T14:51:30"

**Comment by DocRoms** [comment]
Hello @vvatelot . En testant ce matin, je n'ai pas reproduit cette erreur. 
![ResilioSolutionResults](https://user-images.githubusercontent.com/12815769/190891462-c862a5c0-84fa-474f-929e-4cb02ac9f434.png)

J'ai testé au moins une 50aine de site ce Week-end, et je n'ai jamais eut ce cas non plus 😅 . 

As-tu cette erreur lors de tests sur d'autres sites ? Quel navigateur utilises-tu ? As-tu toujours cette erreur sur resilio-solutions.com ?

**Comment by vvatelot** [comment]
Hello, alors moi je n'ai pas constaté le problème, c'est @Amael-PE :wink: 
Peut être peux tu nous donner plus de contexte ? Navigateur utilisé ? :smile:

**Comment by Amael-PE** [comment]
Firefox 104.0.2

**Comment by Amael-PE** [comment]
Ca ne se produit pas sur toutes les URL...

**Comment by AwebsomeFr** [comment]
Bonjour @Amael-PE, 
Merci pour ce retour. Je viens de tester de mon côté ce jour avec Firefox 107, Chrome 106 et Edge 106, tout est OK.
Le problème persiste-t-il encore à ce jour ?

@Bastou, nous utilisons la méthode `toLocaleString` sans argument côté client ([documentation MDN de la méthode](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)). C'est en ligne 157 de SiteAnalysisResult.js. Cela pourrait-il venir de là ? Faudrait-il spécifier `fr-FR` en argument ? Il n'est pas exclu que la configuration système du client l'emporte actuellement.

**Comment by Bastou** [comment]
Je ne reproduis pas non plus de mon côté sur Firefox.

**Comment by AwebsomeFr** [comment]
Ok, puisque le problème n'est plus reproductible, et dans la mesure où il n'était pas bloquant à l'usage, je propose de le considérer comme étant résolu.
