### ISSUE TITLE
Unité manquante ou inadaptée

### ISSUE THREAD

**Issue by Amael-PE** [cnumr/EcoIndex#136]
Page de résultats, on a :
``` 
27.6 l
consommation
d’energie primaire
```
L'unité est, soit incomplète/manquante, soit inadaptée.
On s'attend à des MJ, des kWh à la limite, voire des litres d'essence

**Comment by vvatelot** [comment]
Merci @Amael-PE pour cette issue !
On parle bien de ça ?
![image](https://user-images.githubusercontent.com/12939091/190857185-c7b3b6ad-8a54-4057-9c72-599a85a5ceb8.png)

Bonne question... @DocRoms @aureliebaton votre avis ?

**Comment by Amael-PE** [comment]
Exact !

**Comment by DocRoms** [comment]
Hello @Amael-PE @vvatelot . 
Je penses que l'unité est présente "en litre" et est à mettre en relation avec la consommation d'eau potable utilisée par le numérique et présentée en dessous. Néanmoins, j'avoue que l'on ne s'attends pas du tout à ça avec l'indication `consommation d'énergie primaire`. 

Vu que ça soulève des questions et que ça n'est pas clair, mieux vaut soit changer l'unité, soit la compléter, soit changer l'indication dessous en étant plus précis. 

De plus, je pensais que l'unité était à prendre en compte en matière `d'eau potable` et non pas `d'eau` "tout court" est-ce bien le cas ? Si c'est bien le cas, il faudrait peut-être l'indiquer dans la description plus basse, 

![EauEcoINdexUnit](https://user-images.githubusercontent.com/12815769/190892080-b0e893e2-9120-47dd-aa75-f31e91a0559a.png)

Concernant cette description, je viens de constater que le lien sur `[Mise en perspective des impacts écologiques du numérique](https://ecoindex.neutral.hosting/resultat/?id=61c3aa70-c4c4-4028-a296-1dae16334250#mise-en-perspective)` ne fonctionne plus / pas ?

**Comment by aureliebaton** [comment]
@Amael-PE @vvatelot @DocRoms Bien vu ! EN fait, il s'agit sûrement d'un mauvais copié-collé ;)
Dans la maquette à la base on avait ça 
<img width="585" alt="Screenshot 2022-09-19 at 14 25 00" src="https://user-images.githubusercontent.com/85348619/191016795-1a60317a-96af-42a3-ad1d-cee8e8bb7fa3.png">

**Comment by aureliebaton** [comment]
Pour le lien, merci @DocRoms, il devrait effectivement pointer sur https://raphael-lemaire.com/2020/02/02/mise-en-perspective-suite/

**Comment by AwebsomeFr** [comment]
J'ai commencé une PR : 
- Le lien a été mis à jour
- L'intitulé et le logo pour l'estimation en eau aussi.

Pour l'unité de mesure, c'est plus délicat. J'ai a priori 
* `"<span class='footprint-result' data-int='water' data-unit='cl'>0</span>"` en JS
*  `.footprint-result::after { content: attr(data-unit); padding-left: 0.4em; }` en CSS. On récupère donc l'attribut défini pour injecter l'unité en CSS.
* Et pourtant, au rendu, dans le HTML, on a un `data-unit="l"` venu de nulle part.

Quelque chose prime sur tout ça, mais quoi ?

**Comment by AwebsomeFr** [comment]
Ok, je pense avoir trouvé.

Je ne comprends pas encore toute la logique, mais les unités semblent définies dans la fonction `_updateFootprintResultFromSelect`. 

Il est prévu cl, l, gCO2 et kgCO2e. Sauf que dans un premier cas, on a un facteur de 100 (100cl pour 1 L), dans l'autre, un facteur de 1000 (1000g pour 1 Kg). 

Quelque chose doit cafouiller par là.

**Comment by Bastou** [comment]
@AwebsomeFr vu que j'avais fait la méthode de calcul avec le select à l'origine je peux reprendre la pr pour corriger ça si tu veux ?

**Comment by yaaax** [comment]
Go @Bastou :) J'ai jeté un oeil et je vois que c'est ton code, tu iras plus vite !

**Comment by Bastou** [comment]
Hello @yaaax @AwebsomeFr j'ai fix le système de changement d'unité sur les résultats de l'empreinte sur #156

**Comment by aureliebaton** [comment]
Est-ce qu'on peut fermer cette issue du coup ?

**Comment by yaaax** [comment]
Fixed by 52fe12d
