### ISSUE TITLE
GitHubPage Configuration

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#14]
We want to have a demo with `github Page`, We must to activate githubPage on this repository and test hugo initialisation with it.

**Comment by DocRoms** [comment]
- [x] Configuration GitHUb Page is done
- [ ] Test Hugo when the `init Hugo` PR was merged

**Comment by rlemaire** [comment]
Isn't this issue able to be closed ?

**Comment by yaaax** [comment]
We now host EcoIndex on [Neutral Hosting](https://neutral.hosting/)
