### ISSUE TITLE
Soucis au niveau des type de tests effectués - Front REGEX

### ISSUE THREAD

**Issue by DocRoms** [cnumr/EcoIndex#142]
Ce soucis correspond à une partie de la discussion ci-dessous. C'est un soucis Front.

Dans la regex validant l'URL qui va être envoyée à l'API. Il faut que l'on valide le fait que ça ne soit pas une ressource .js/.css/.png/.jpeg... Mais il faut aussi penser que l'on peut avoir des pages en .php/.html/.htm/.asp...

### Discussed in https://github.com/cnumr/EcoIndex/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **DocRoms** September 17, 2022</sup>

@vvatelot m'a également transmis la liste du `top 50` des sites testés sur ecoIndex v2, et j'ai pu constaté que nous avions la possibilité de tester non pas que des pages, mais aussi des ressources ou des pages API. Ainsi, si on teste une route API qui renvoie du JSON, ou un fichier CSS, on s'octroie un grade A, sans difficulté. 
Ici il faut que l'on fasse deux vérifications : 
- la première coté FRONT, en testant le type d'URL et en vérifiant que l'on tente pas de tester une ressource (JS/CSS/PNG/...)
- la seconde coté API, en testant le `content-type` que celui-ci retourne bien du `text/html`.

Les deux vérifications sont essentielles, la première va éviter de faire trop d'appels à l'API, la seconde valider le résultat. </div>

**Comment by AwebsomeFr** [comment]
Pas facile facile.
Côté client, il va être difficile de tout parer je crois, mais essayons de restreindre au maximum.

1. Peut commencer par
    * http://
    * https://
    * http://www
    * https://www
    * www
2. Est suivi d'un  .
3. Contient X chiffres, caractères et certains caractères spéciaux (. pour les sous-domaines, - pour séparateurs, etc).
4. Contient au moins 1 nom de domaine de premier niveau connu (.com, .fr, etc.)
5. Peut comprendre encore chiffres et caractères, y compris spéciaux (/ pour les dossiers, & pour les queries, etc.)
6. Peut éventuellement se terminer par .php, .asp, etc ?

**Comment by vvatelot** [comment]
Est ce que ça peut être utile à la discussion ? https://stackoverflow.com/a/43467144

**Comment by yaaax** [comment]
Le lien envoyé par @vvatelot me semble très pertinent !

**Comment by AwebsomeFr** [comment]
Cela ne semble pas couvrir le cas `www.example.com` (à juste titre ?) que l'on supporte je crois actuellement ?

Dans tous les cas, il faut imaginer une seconde passe, toujours côté client, pour s'assurer qu'on ne cible pas une ressource autre qu'un point d'entrée (une image, par exemple). On peut donc imaginer une liste blanche des terminaisons possibles dès lors que l'URL est établie au préalable comme étant conforme.

- Slash de fin optionnel éventuel
- Si contient un . après le dernier slash, s'assurer que cela forme une extension "racine de page" acceptée (htm, html, php, etc) 

Cela vous semble-t-il cohérent ?

**Comment by AwebsomeFr** [comment]
Il me semble que l'idée de @DocRoms était surtout d'éviter l'analyse de ressources non appropriées ; si cela est au moins vérifié côté serveur dans un premier temps, pour que la base de données ne soit pas saturée de ce type d'analyse, je pense que nous pouvons nous en contenter dans un premier temps (tout en gardant cela comme étant prioritaire pour la suite).

**Comment by yaaax** [comment]
Je vois cette liste :
https://en.wikipedia.org/wiki/List_of_file_formats#Web_page

Mais je ne sais pas si c'est exhaustif…
