### ISSUE TITLE
Afficher les captures d'écran 

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex#152]
# Afin de

Permettre de visualiser la page qui a été 

# Je veux

Afficher la capture d'écran qui est faite lors de l'analyse ecoindex de la page 

# Infos

La capture d'écran est déjà activée et disponible sur la route `/screenshots/v1/{id}.webp`

**Comment by jpkha** [comment]
@vvatelot On peut fermer l'issue ?

**Comment by bgatellier** [comment]
Something like that?

![image](https://github.com/cnumr/EcoIndex/assets/1890804/89b4399f-264c-4673-8d29-1ca326851681)

Or more like that?

![image](https://github.com/cnumr/EcoIndex/assets/1890804/1311da63-668d-447e-b76e-4a10859b08ca)

**Comment by vvatelot** [comment]
Hum, in my mind, I would have said something like 
![image](https://github.com/cnumr/EcoIndex/assets/12939091/83d30e54-f580-47de-8767-cd0c04f4ed7e)

This way, it does not impact too much the current display... What do you think ?

**Comment by bgatellier** [comment]
Do the images always have the same ratio (eg. 1920x1080)?
Or could they have different one according to the website for example?
To make sure the frontend integration will take care of every case

**Comment by vvatelot** [comment]
> Do the images always have the same ratio (eg. 1920x1080)? Or could they have different one according to the website for example? To make sure the frontend integration will take care of every case

Yes, for now all images have the same ratio. It could be different, but for now, we only run analysis with this window size
