### ISSUE TITLE
Config files type

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/EcoIndex#16]
Configuration files should share the same extension. 
Do we keep JSON or TOML ?
(I vote for JSON)

**Comment by rlemaire** [comment]
I created a PR for that.

**Comment by yaaax** [comment]
We now have many config files…
- hugo (config.**toml**)
- npm (package.hugo.**json**, package.**json**)
- Babel (babel.config.**js**)
- GitHub (deploy.**yml**, dependabot.**yml**, etc.)
- rc files : .browserlistsrc, .markdownlintrc, .prettierrc

Unfortunately sometimes the format is not a choice.
Happy to hear comments on that anyway.

Let's move on and close that issue?
