### ISSUE TITLE
Ajout d'une image pour opengraph

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex#193]
# Afin de 

Améliorer le rendu du lien partagé dans les outils de réseaux sociaux

# Je veux

Ajouter une image du logo ecoindex (ou mieux ?) dans les metadonnées opengraph du site

**Comment by vvatelot** [comment]
Quelle image peut on faire apparaitre, @aureliebaton @yaaax ?

**Comment by aureliebaton** [comment]
Le logo ça me semble une bonne idée, et ça a le mérite d'être léger. Mais je suis preneuse de l'avis de @yaaax

**Comment by vvatelot** [comment]
Pour info, j'ai beau suivre la doc https://gohugo.io/templates/internal/#open-graph, je n'arrive pas à faire apparaitre les données opengraph sur le rendu html des pages... @yaaax tu arriverais à reprendre la main ?

**Comment by yaaax** [comment]
Oui je suis dessus !
