### ISSUE TITLE
[Enhancement]: Permettre de visualiser les impacts selon un trafic personnalisé 

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/EcoIndex#201]
Actuellement, la page de résultats permet d'estimer les impacts d'un service numérique selon un nombre de visites prédéfini (10, 100 et 1000).

Il faudrait pouvoir déterminer manuellement ces multiplicateurs.

**Comment by tbroyer** [comment]
Ces impacts sont-ils d'ailleurs réellement linéaires ?

**Comment by yaaax** [comment]
> Ces impacts sont-ils d'ailleurs réellement linéaires ?

Très bonne remarque !
Je n'ai pas la réponse 😅

**Comment by tbroyer** [comment]
Si les chiffres sont issues d'une "ACV de bout en bout en cycle de vie complet" ([source](https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale)) alors vraisemblablement non. Confirmé d'ailleurs par [l'article en lien](https://blog.octo.com/sous-le-capot-de-la-mesure-ecoindex/#:~:text=On%20comprend%20maintenant,produit%2C%20achemin%C3%A9%2C%20install%C3%A9%E2%80%A6)

> On comprend maintenant que consulter la page web que l’on analyse avec Ecoindex n’est pas directement et physiquement responsable de 3 cl d’eau et 2 gCO2e.
> 
> Visiter 1000 fois à la suite cette page n’émet pas 30 litres d’eau et 2 Kg d’équivalent CO², et enfin ne pas visiter cette page du tout ne conduit pas à 0 impact, vu que le matériel a quand même été produit, acheminé, installé…

À titre personnel, je ne comprend pas ces indicateurs et je les trouve trompeurs (encore plus si on leur applique le nombre de visites comme simple multiplicateur)

**Comment by JulienWilhelm** [comment]
Remarque pertinente, merci @tbroyer !
Il va falloir que l'on réfléchisse à la question.
