### ISSUE TITLE
[Bug]: Chargement infini du loader en cas de retour arrière dans l'historique depuis la page de résultats

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/EcoIndex#202]
### Que s'est il passé ?

Après avoir lancé une analyse, depuis la page des résultats, si l'on clique sur le bouton précédent du navigateur (reculer d'une page), le retour se fait bien sur l'accueil, mais le popup du loader apparait et tourne en boucle tant qu'il n'est pas annulé manuellement (le trafic réseau semble figé, à confirmer).

### Sur quel navigateur avez vous rencontré ce problème ?

Firefox

### Sur quel device rencontrez vous le problème ?

PC

**Comment by yaaax** [comment]
Peut-être parce-qu'on ne ferme pas la popup au moment de la réponse ?
Je ne reproduis pas systématiquement.
@JulienWilhelm as-tu un cas de reproduction systématique ?
Si oui peut-être que tu peux essayer un code de ce type en local, dans `index.js` :

```
function cleanApp() {
	EcoIndexDialog.close();
}

// clean app before the window is unloaded
window.addEventListener("beforeunload", cleanApp);
```

**Comment by tbroyer** [comment]
Note: `beforeunload` rend la page inéligible au bfcache dans Firefox, et on n'a pas besoin ici de la capacité de `beforeunload` à demander à l'utilisateur de confirmer la navigation; il vaudrait mieux utiliser `pagehide` ici.
https://web.dev/bfcache/#optimize-your-pages-for-bfcache

**Comment by JulienWilhelm** [comment]
@yaaax, a priori le bug persiste sur la version déployée (je confirme, systématiquement de mon côté), mais ne se produit pas sur la version à date du dépôt.

Cela a donc été corrigé entretemps (?)

**Comment by yaaax** [comment]
La version à date du dépôt n'est-elle pas la version déployée ?
Il faudrait tester en local avec
```
hugo serve --env production
```
pour voir si le problème est reproduit (= simulation de l'environnement de production en local)

**Comment by JulienWilhelm** [comment]
J'ai testé à l'instant avec `hugo serve -e production` : ce bug ne se produit toujours pas en local.

(pour info ` -e, --environment string  = build environment`)
