### ISSUE TITLE
Ajouter un outil d'analytics

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex#204]
Utiliser https://plausible.io/ ou https://fr.matomo.org/

**Comment by jpkha** [comment]
Une raison de proposer l'un des deux ? J'étais tombé sur https://umami.is/ qui à l'air top aussi.
Après ça dépendra du besoin voulu. Quels sont les paramètres que nous souhaitons récupérer ?

**Comment by JulienWilhelm** [comment]
Y-a-t-il une BDD MySQL de dispo pour Matomo ? À savoir qu'il faut malgré tout ruser avec ce dernier (même si configuré pour respecter la vie privée) pour ne pas être bloqué par les bloqueurs de publicités / tracking.

**Comment by vvatelot** [comment]
Alors après, apparemment notre hébergeur compile les logs et permet de les visualiser avec awstats. Je vais creuser cette piste qui pourrait nous permettre de ne rien avoir à faire au final...
