### ISSUE TITLE
Count HTTP Requests errors

### ISSUE THREAD

**Issue by mfr75** [cnumr/EcoIndex#21]
Count HTTP Requests errors // there is a bug on http https redirect on counting requests on Ecoindex.

in french

> Pour cette question de test qui affiche 0 ou 1 requête j'ai souvent le soucis lorsqu'il y a une redirection (adresse http renseignée au lieu de https par exemple), l'extension navigateur est généralement plus fiable si on répète les mêmes conditions de test (et je suppose que ça évite aussi de trop surcharger le serveur d'ecoindex.fr si nous n'avons pas besoin de diffuser les résultats).

**Comment by yaaax** [comment]
@vvatelot to keep open or not?

**Comment by vvatelot** [comment]
I think it is solved... 🤔
