### ISSUE TITLE
Barème des scores/grades

### ISSUE THREAD

**Issue by pirmax** [cnumr/EcoIndex#251]
Bonjour,

Je cherche tant bien que mal le barème des scores.

Quelle est la plage de score pour le grade A, puis pour le grade B, etc...

Je vous remercie pour votre aide précieuse.

Maxence.

**Comment by vvatelot** [comment]
Bonjour @pirmax merci pour la question !
Tu trouveras ça ici : https://github.com/cnumr/ecoindex_reference/blob/main/ecoindex_reference.json

On est en train de réorganiser les projets pour qu'ils se basent sur cet unique de valeurs références

**Comment by tbroyer** [comment]
On trouve ces valeurs dans le projet https://github.com/cnumr/ecoindex_reference

**Comment by pirmax** [comment]
Oui, parfait, merci à vous deux, j'ai pris connaissance de ce fichier JSON juste après avoir posé la question ici.

Belle journée à vous.

Maxence Rose.
