### ISSUE TITLE
[Évolution] Interet du nombre de requêtes avec HTTP/2

### ISSUE THREAD

**Issue by obeone** [cnumr/EcoIndex#253]
Avec l'utilisation de HTTP/2, le nombre de requêtes ne semble plus forcement être pertinent comme indicateur. En effet, le côté asynchrone des demandes font qu'une seule connexion peut faire transiter rapidement et efficacement de nombreuses ressources (avec cache intelligent côté serveur etc).
A contrario, les méthodes souvent utilisées jusqu'ici pour limiter le nombre de requêtes (Sprite CSS par exemple), peuvent se trouver alourdir le tout (parce que souvent tous les éléments du sprite ne sont pas nécessaire dans la page en cours, parce qu'il y a de vieux éléments qui trainent parce qu'un sprite peut être chiant a mettre à jour...). En plus, des manipulations sont demandées au navigateur pour chacune de ces images, ce qui va être consommateur.

Aujourd'hui, [97% des navigateurs](https://caniuse.com/?search=http2) supportent HTTP/2. C'est un peu moins le cas des serveurs, mais ne serait-il pas judicieux de ne pas compter le nombre de requêtes sur un serveur supportant HTTP/2 ? (Ou sinon, compter par contre le nombre d'hosts différents, puisque ici en effet, il y aura au moins une connexion par host).

NB : [Mozilla indique](https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Images/Implementing_image_sprites_in_CSS) "Avec HTTP/2, il peut être plus judicieux d'utiliser de nombreuses « petites » requêtes."

**Comment by vvatelot** [comment]
Je suis plutôt en phase. Il faudrait revoir cet indicateur et le pondérer en fonction de :
- Nombre de requêtes par domaine
- Quel est le nombre de requêtes max autorisées par le navigateur en parallèle
- ...?

**Comment by tbroyer** [comment]
Sur le sujet HTTP/2, j'ai fouillé les archives (notez les dates !) :

* https://groups.google.com/g/ecoconceptionweb/c/bBn3nZ2Ici8/m/gb_KU-TXBgAJ (15 mai 2016)

    > “the ingress traffic bandwidth was reduced significantly (close to 50%) after we enabled HTTP/2” — Source: https://blogs.dropbox.com/tech/2016/05/enabling-http2-for-dropbox-web-services-experiences-and-observations/
    > 
    > Est-ce que ça justifierait pas une nouvelle bonne pratique ? Au moins pour les sites qui utilisent déjà HTTPS.

* https://groups.google.com/g/ecoconceptionweb/c/d--cf5m0Eno/m/U4WLtOtrAAAJ (3 déc. 2020)

    > Bonjour,
    > La plupart des outils d'audits lié à l'éco-responsabilité, comme le plugin pour EcoIndex, demandent d'avoir le moins de requêtes HTTP possibles. Pourtant, depuis que le protocole HTTP/2 est arrivé, nombre d'articles disent qu'il n'est plus nécessaire de concaténer les ressources. De plus, cela nuirait à la gestion du cache puisqu'au moindre changement dans un des modules JavaScript par exemple, cela invaliderait tout ce qui a été mis en cache côté JS...

* https://groups.google.com/g/ecoconceptionweb/c/wqOGBotUW1g/m/LWYIyiXUDgAJ (25 janv. 2021)

    > Vaut-il mieux faire une grosse requête (sprite sheet) ou 30 petites pour récupérer des images ?

* https://groups.google.com/g/ecoconceptionweb/c/JJa9WlpqxHM/m/8rne9In4DQAJ (29 avr. 2022)

    > Depuis HTTP/2 l'intérêt de faire le moins de requêtes possible s'est un peu réduit, (il faut toujours en faire le moins possible, mais il y a moins de "gain" qu'avec HTTP/1).

**Comment by JulienWilhelm** [comment]
Hum... Je ne suis pas tout à fait d'accord.

L'intérêt d'HTTP/2, c'est la compression des en-têtes de requêtes et le multiplexage. 

Définition du multiplexage selon Antidote : 

> Division d’une voie de transmission commune en plusieurs voies distinctes qui peuvent transmettre en même temps des signaux indépendants dans le même sens / Combinaison de signaux indépendants en un seul signal destiné à être transmis sur une même voie.

D'une part, plus de requêtes, c'est forcément plus d'en-tête de requêtes, quelque soit le nombre différents de domaines sollicités.

D'autre part, il n'y a je crois aucune garantie à ce que 10, 20, 50 requêtes effectuées vers un même domaine soient effectivement toutes *groupées* (je me méprends peut-être, mais si cela se trouve, seules 5, 8, 15 ou que sais-je pourraient l'être à un moment, plus ou moins à un autre). C'est d'autant plus certains sur des requêtes asynchrones, qui auront pourtant une même origine.
