### ISSUE TITLE
[Bug]: infos contradictoires

### ISSUE THREAD

**Issue by revolunet** [cnumr/EcoIndex#265]
### Que s'est il passé ?

Bonjour, je n'ai pas réussi à retrouver d'où venait la correspondance entre CO2 et kms parcourus.

[Ici](https://github.com/cnumr/EcoIndex/blob/master/content/fr/result/_45_ca-veut-dire.md?plain=1):

> **1 kg CO2e** équivaut à un trajet d’environ **5 km en voiture**.

Et [ici](https://github.com/cnumr/EcoIndex/blob/master/layouts/partials/widgets/result-empreinte.html#L47) :

> 1 kg CO2e équivaut à un trajet d’environ **3 km en voiture**.

Quelle serait le plus realiste ?

**Comment by yaaax** [comment]
Bien vu.
En regardant sur le site de l’Ademe (https://agirpourlatransition.ademe.fr/particuliers/bureau/deplacements/calculer-emissions-carbone-trajets) je vois que c’est plutôt 5 que 3.

On change juste le 3 en 5 ?

**Comment by revolunet** [comment]
Ca semble plutôt être vers les 5 en effet
