### ISSUE TITLE
Add stale action

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex#277]
# In order to

Clean up the backlog and only keep the accurate issues / PR

# I want to 

Implement https://github.com/actions/stale so it will automatically send reminders to people watching PR / issues to ask them if they are still up to date

**Comment by tbroyer** [comment]
I personally hate it when issues are auto-closed with such bots. I see it as a sign that issues aren't given enough love/time, which means the either the maintainer team doesn't care enough or isn't "sized" to handle them, both are a negative signal regarding maintenance of the project, so possibly a sign that maybe I shouldn't use it.

I subscribe :100: to these:

> Radio silence on a bug report is far better than this stale bot / "we value your feedback but..." bull shit.

— https://twitter.com/JakeWharton/status/1295746357312073728

> Bugs are bugs. Feature requests are feature requests. Don't use a bot to cover for your broken process and inability to triage.
> 
> Leave bugs open. Every few months there's stories of bugs fixed after single or double-digit years on here or HN or Reddit. Leave feature requests open or simply respond "no" or "not for the foreseeable future" and close. By a human.
> […]
> I'm left with a stale taste in my mouth from the bot.
> 
> [Some] issues […] were never replied to and hit by the bot. It disincentivizes me from filing anything in the future.

— https://twitter.com/JakeWharton/status/1362078930379952128
