### ISSUE TITLE
[Bug]: Lien vers le badge

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex#292]
### Que s'est il passé ?

Le lien vers le badge n'est pas correct (en tout cas sur la page de résultat...)
https://www.ecoindex.fr/resultat/?id=cc05241a-21a0-4006-868a-6d2ccc2ccb58

**Comment by vvatelot** [comment]
Tiens, je n'avais pas vu que ça avait été introduit seulement depuis la dernière MEP...
Je dirais que dans l'immédiat on peut juste rediriger vers le projet du badge: https://github.com/cnumr/ecoindex_badge et voir par la suite si on intègre ça plus proprement directement dans le site..? Tu en penses quoi ?

**Comment by vvatelot** [comment]
Je pense qu'il y a effectivement une petite mise à jour à faire au sein du collectif pour comprendre ce qui était la cible initiamelement et est ce que c'est toujours d'actualité ?... Je relance en interne... Mais pour l'instant, je dirais que oui, on supprime la section sur la page des résultats et voir pour proposer quelque chose de plus clean une fois que c'est validé

**Comment by bordage** [comment]
Perso, je trouve étrange de n'afficher le badge que pour un score de A ou B. Le badge devrait s'afficher quel que soit le score EcoIndex.

**Comment by vvatelot** [comment]
Ok, dans ce cas je pense qu'on peut remettre ce paragraphe dans le site en faisant le lien avec le projet https://github.com/cnumr/ecoindex_badge si tout le monde est ok

**Comment by bordage** [comment]
+1

Le lun. 22 janv. 2024 à 21:07, Vincent Vatelot ***@***.***> a
écrit :
