### ISSUE TITLE
[Bug]: Réutilisation d'un rapport

### ISSUE THREAD

**Issue by wokier** [cnumr/EcoIndex#300]
### Que s'est il passé ?

Quand je réutilise une analyse précédente tel que
https://www.ecoindex.fr/resultat/?id=9c564ff6-850b-4afa-841c-53bc55429949
et que je clique sur le bouton "retester"
après un moment d'attente (la nouvellle analyse)
Je suis redirigé vers la page
https://www.ecoindex.frundefined/?id=571e26ae-6e80-44fd-a6ca-2b0f97877632
le coutournement est de remplacer 'undefined' par '/resultat'
(sur macos)

### Sur quel navigateur avez vous rencontré ce problème ?

Firefox, Autre

### Sur quel device rencontrez vous le problème ?

Autre

**Comment by vvatelot** [comment]
**🙏🏻 merci pour ta contribution**! 🙂
Il y a déjà une issue ouverte à ce sujet... #297 on essaye de regarder ça rapidement...

**Comment by wokier** [comment]
Effectivement, c'est la même anomalie.
Ma langue/locale est en anglais.

**Comment by vvatelot** [comment]
fixed by #304
