### ISSUE TITLE
[Bug/Enhancement]: Timeout fréquent

### ISSUE THREAD

**Issue by heyflo** [cnumr/EcoIndex#327]
### Que s'est il passé ?

Depuis quelques semaines, il est impossible de faire plus de 2 tests d'affilés sans que le site EcoIndex.fr crash.
Soit le serveur est surchargé, soit il doit y avoir une (des?) erreur(s) à l'exécution d'un test ce qui provoque une surcharge au niveau du serveur.

Egalement, avons-nous une solution alternative pour pouvoir tester de manière assez fréquente sans relancer via le site ?

En vous remerciant,
Cordialement

### Sur quel navigateur avez vous rencontré ce problème ?

Chrome

### Sur quel device rencontrez vous le problème ?

PC

### Un message d'erreur est il apparu ?

```shell
Oh oh, dommage…

L’analyse n’a pas pu aboutir.

Veuillez réessayer plus tard
```

**Comment by vvatelot** [comment]
Merci pour ce message @heyflo. Est ce possible d'avoir plus d'informations sur la reproductabilité de ce problème:
- Quelles urls sont concernées ?
- À quelle fréquence lances tu des analyses ?
- Y a t il des traces réseaux pertinentes dans les dev tools chrome ?

Les éléments à prendre en considération aujourd'hui:
- Ecoindex est un service gratuit grand public sans engagement de disponibilité
- Le service tourne sur un "petit" VPS
- Le service analyse plus de 1000 pages par jour
- Il n y a que 2 workers pour les analyses. Autrement dit, on ne traite que 2 analyses simultanément et les autres doivent attendre leur tour
- Nous avons constaté des coupures de services ces derniers temps qui amènent à des indisponibilités du service. Nous sommes en contact avec l'hébergeur pour régler ces problèmes et améliorer la situation

Je suis désolé que l'expérience ne soit pas parfaite sur le site ecoindex.fr et nous faisons tout notre possible pour satisfaire le plus grand nombre.

Il existe des outils qui permettent aux développeurs (notamment) de faire tourner Ecoindex en local:
- [GreenIT Anlysis](https://github.com/cnumr/GreenIT-Analysis) pour analyser directement une page dans son navigateur
- [Ecoindex CLI](https://github.com/cnumr/ecoindex_python_fullstack/tree/main/projects/ecoindex_cli#ecoindex-cli) pour lancer des analyses massives
- [Installer sa propre API](https://github.com/cnumr/ecoindex_python_fullstack/tree/main/projects/ecoindex_api#ecoindex-api) (la même qui est utilisée sur le site www.ecoindex.fr)

Puis je me permettre de déplacer ce message dans la section discussion du projet qui me semble plus adaptée ?
