### ISSUE TITLE
[Bug]: Formula issues?

### ISSUE THREAD

**Issue by FANMixco** [cnumr/EcoIndex#333]
### Que s'est il passé ?

I'm wondering how accurate is your calculator (don't take it personally, I want your solution to succeed). I wasn't aware of its existence until I wrote an [article](https://dev.to/fanmixco/can-you-make-your-website-green--1lb7) and someone suggested testing it. However, I noticed considerable discrepancies between Ecograder, Website Carbon Calculator, Beacon, and yours.

This is a screenshot of my [personal website's results](https://federiconavarrete.com) per solution:

![Previews results](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/sfr4p1eus0dnw3lcltjz.png)

As we can see the differences are massive. 

I'm wondering why your results are extremely different since my results moved from 0.191g on average to over 2g per loading. It means that my website is 1047% more polluting based on your calculator. It sounds quite strange. Something is not right. Either all other solutions have wrong formulas or yours is considering significantly different variables that nobody else has thought about them.

I'd like to know your conclusions.

_Sources:_
- [Website Carbon Calculator](https://www.websitecarbon.com/website/federiconavarrete-com/)
- [Digital Beacon](https://digitalbeacon.co/report/federiconavarrete-com)
- [Ecograder](https://ecograder.com/report/icdJEqqkqWC05UF4qszM38bW)
- [Carbon Calculator](https://websiteemissions.com/)
- [Ecoindex.fr](https://www.ecoindex.fr/en/result/?id=8088b19b-f55a-4a2e-ada4-edf6462f6478#score-details)

**Comment by yaaax** [comment]
Hi Federico,
You should have a look at the "Analysis methodology" section at page [How does it work?](https://www.ecoindex.fr/en/how-it-works/).

> When an analysis is launched, the requested page is loaded in a real Chrome browser and play the following scenario:
> 
> Launch a headless Chrome browser with no-sandbox, disable-dev-shm-usage options and goog:loggingPrefs capabilities at {"performance": "ALL"}
> Open the page without local data (cache, cookies, localstorage…) with a resolution of 1920x1080px
> Wait 3 seconds
> **Scroll down**
> Wait 3 seconds again
> Close the page

The difference with other tools probably resides in the **scroll down**.

Cheers

**Comment by FANMixco** [comment]
> Hi Federico, You should have a look at the "Analysis methodology" section at page [How does it work?](https://www.ecoindex.fr/en/how-it-works/).
> 
> > When an analysis is launched, the requested page is loaded in a real Chrome browser and play the following scenario:
> > 
> > 1. Launch a headless Chrome browser with no-sandbox, disable-dev-shm-usage options and goog:loggingPrefs capabilities at {"performance": "ALL"}
> > 2. Open the page without local data (cache, cookies, localstorage…) with a resolution of 1920x1080px
> > 3. Wait 3 seconds
> > 4. **Scroll down**
> > 5. Wait 3 seconds again
> > 6. Close the page
> 
> The difference with other tools probably resides in the **scroll down**.
> 
> Cheers

Hi @yaaax, I have some observations. I ran it as suggested in Incognito and as a Guest mode. Certain results changed the weight. Only the first time I ran it, the weight was reduced to 0.6 MiB, then, it increased the website site to 1.3 MiB odd. The ranking partially increased, but the amount of calls and objects were still complaints. Something that is not considered anywhere else to reduce your CO2 footprint.

Do I think the scroll is not considered in the other solutions? I don't think so. It's considered. Ecograder always reported some images at the bottom of my website. They came from lazy-loaded `iFrames`. That's why, I decided to implement a lazy loading image strategy, and the results improved significantly. Therefore, the scroll is considered in all other calculators.
