### ISSUE TITLE
Intégration page de résultats : composant "Collapsible Section" et lien vers ancre

### ISSUE THREAD

**Issue by yaaax** [cnumr/EcoIndex#54]
Intégration :
  - du composant "Collapsible Section"
  - des liens vers les ancres (grace aux ids de titre)

**Comment by Bastou** [comment]
J'ai modifié le composant collapse pour ne pas qu'on puisse focus un lien dans le contenu. Si il manque peu de modifs pour qu'il soit accessible est-ce qu'on a besoin de le remplacer ? 
Je m'étais basé sur : https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions

**Comment by yaaax** [comment]
Écoute, c'est très bien, pas besoin de remplacer ;)
J'ai ajouté le helper manquant et ça fonctionne bien.

**Comment by yaaax** [comment]
Link to "Détails du code" fixed by https://github.com/cnumr/EcoIndex/commit/8e7ba21334e886ad6bafde5749338b059b619204
