### ISSUE TITLE
Parcours analyse depuis la page d'accueil

### ISSUE THREAD

**Issue by Bastou** [cnumr/EcoIndex#59]
Gestion du parcours d'analyse avec : 
- post du formulaire avec redirection vers la page analyse
- requête post vers l'api sur la page analyse et récupération du résultat
- redirection vers la page résultat avec les bons éléments en paramètre de l'url

**Comment by yaaax** [comment]
See a05c8fd0f45f9c5e660dec00fad97d7afcc542f1
