### ISSUE TITLE
Move strings to i18n folder

### ISSUE THREAD

**Issue by yaaax** [cnumr/EcoIndex#69]
Look inside :
- [Widget result-appreciation](https://github.com/cnumr/EcoIndex/blob/master/layouts/partials/widgets/result-appreciation.html)
- [Widget result-detail-score](https://github.com/cnumr/EcoIndex/blob/master/layouts/partials/widgets/result-details-score.html)
- [Widget result-empreinte](https://github.com/cnumr/EcoIndex/blob/master/layouts/partials/widgets/result-empreinte.html)
- [Widget result-intro](https://github.com/cnumr/EcoIndex/blob/master/layouts/partials/widgets/result-intro.html)
…and maybe more

You will find strings that should be inside i18n folder in order to be translated.

**Comment by AwebsomeFr** [comment]
Some strings need to query __a singular/plural translation__. For instance, in this snippet : 

`<span class="result-notation-info-number"><span data-int="nodes">0</span> éléments</span>`

"éléments" could be : 
* "element" or "elements" in english
* "élément" or "éléments" in french.

For now, we temporary get variables from URL with JS. But il will change. When this change will be ok, we'll can use a variable like `elementCount` to specify at the page rendering time the number of elements and match with /i18n/en.toml and /i18n/fr.toml files to automatize the translation.

Example : {{ i18n `Request` elementCount }} 
(with backtips around Request)

Note : please check in /i18n/en.toml and /i18n/fr.toml that the corresponding definitions exist, else, create them.

**Comment by yaaax** [comment]
Implemented with ExecuteAsTemplate.
See https://github.com/gohugoio/hugo/issues/7070#issuecomment-601828633

We now have separated JS files for each language.

Let's see if it works fine, and if it's not too heavy. Then we'll be able to close this issue :)
