### ISSUE TITLE
URL form submission required improvements

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/EcoIndex#72]
- [X] **(done, pr coming)** It **should not be** possible for the user to submit a empty url (currently possible, inits an infinite loading / client-side and-server side checking required).
- [ ]  It **should be** possible for the user to submit an url without have to tip HTTP(s) protocol (currently impossible). Two options. 1. Accept all value and complete on submit. 2. Use pattern attribute to require a complete URL ([using regex](https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url) : it should be specified on UI). In both case, url must be at least a valid domain.

**Comment by yaaax** [comment]
I keep that one even if point 2 is already partly implemented.
Currently "https://" can be added automatically. But we should improve this behaviour to try "http://" in case it failed (?)
For exemple, the current http://ecoindex.fr site…

**Comment by JulienWilhelm** [comment]
Duplicate issue : see #200
