### ISSUE TITLE
Proposal to improve the score calculation

### ISSUE THREAD

**Issue by IGLOU-EU** [cnumr/EcoIndex#74]
Hi there,

Currently, this tool provides an estimate of the Environmental Footprint. 
But without taking into account some of the most important points.
- Interpretation of the JavaScript for its execution
- Load generated by the execution of the JavaScript
- The type of server, dirty like AWS or optimized like Infomaniak
- How it is generated, CMS like WordPress or Static like with Hugo

This leads to improbable results like:

SCORE: A 88 / 100
SERVER: CLOUDFLARENET
NOTE: Heavy CPU load
URL: https://webglsamples.org/google-io/2011/40000-objects.html

SCORE: A 79 / 100
SERVER: OVH SAS
NOTE: Hosting without compensation, Multiple JS scripts, WordPress CMS
URL: https://www.centredartpontmain.fr/

SCORE: B 75 / 100
SERVER: O2Switch
NOTE: No JS or Cookies, Static Generation, One page, Hosting with compensation
URL: https://iglou.eu

SCORE: C 62 / 100
SERVER: POSITIVE-USA
NOTE: Almost exclusively text, no JavaScript or cookies, low-tech
URL: https://stallman.org/

SCORE: C 53 / 100
SERVER: FACEBOOK
NOTE: A Lot of JS loaded, tracking, cookies, facebook ...
URL: https://www.instagram.com/p/CeT0ebXKeoF/

To me, these are biases, which give a false image of an online resource.
The calculation of "complexity" seems to be a strong bias in the result, which considers text as "complexity".

What do you think?

**Comment by vvatelot** [comment]
**🙏🏻 Praise:** Thank you for your contribution !

I completely agree with your analysis! The current ecoindex is really basic and is maybe outdated today, as the web and webpages have evolved. I think it's great to keep ecoindex "as it" (maybe, make the samples used to compare results evolve, as they are from 2014...). Ecoindex aims to be a level 1 tool to give you simple indicator.

But yes, it could be great to think about a more evolved tool to take into account contextual parameters... Do you have an idea of the way to do it ?

**Comment by IGLOU-EU** [comment]
So we need a warning message about. I often see this software used as an example for demonstrating "eco-designed" online products, even if they're not.

Even without the JS calculation part, the tool can be updated, or  legacy is ... hardcore ? :D

Yes, I have some ideas about hosting or cms. But not for the JS usage. I'm not a JS guy, you know :p
If we had to make a new software, I would be in favor of a reverse calculation of the results to the current one. Basing on an empty page doesn't make much sense, because a request for an empty page is a waste of resources.
What would you think of a points system? :thinking: 

With the growing interest in free software and a tool to calculate the impact of online tools. I think we can probably use participatory bonuses, for people making the features requested :thinking:

**Comment by vvatelot** [comment]
I think that a workshop should be planned with the people concerned within the collective. Would you be part of it?

IMO, we must have to focus first on the launching of the new ecoindex website release and then move to this rework...

**Comment by IGLOU-EU** [comment]
Hi @vvatelot,
Are you still open to discussion on the subject ? Any news ?
Regards, :)

**Comment by vvatelot** [comment]
Hello @IGLOU-EU , yes of course, still open to discussion! :)
I was not really available lately. Maybe you can join the slack of the Cnumr and we will work on this subject: cnumr.slack.com
